version: "3"

services:
  forum_mysql:
        image: mysql
        container_name: mysql
        volumes:
        - /data/fastapi-forum-docker-mysql:/var/lib/mysql
        ports:
        - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootroot
  forum_redis:
        image: redis/redis-stack
        container_name: redis
        ports:
        - 6379:6379
        - 8001:8001
  forum_fastapi:
        build:
            context: ./backend
        volumes:
        # 挂载当前目录下的 ./backend/app 到容器中的 /app/app
        - ./backend/app:/app/app
        # 如果有脚本也需要热更新，挂载脚本目录
        - ./backend/scripts:/app/scripts
        # 挂载 Poetry 配置文件
        - ./backend/pyproject.toml:/app/pyproject.toml
        - ./backend/poetry.lock:/app/poetry.lock
        ports:
        - 8000:8000
        depends_on:
        - forum_redis
        - forum_mysql
        command: poetry run fastapi dev --host 0.0.0.0 --reload /app/main.py
