[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["apple115 <2567031030@qq.com>"]
# readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
redis = {extras = ["hiredis"], version = "^5.0.8"}
pytest = "^8.3.3"
fastapi = {extras = ["standard"], version = "^0.114.1"}
pydantic = "^2.9.1"
pydantic-settings = "^2.5.2"
fastapi-mail = "^1.4.1"
sqlmodel = "^0.0.22"
python-jose = "^3.3.0"
passlib = "^1.7.4"
pymysql = "^1.1.1"
cryptography = "^43.0.1"
loguru = "^0.7.2"

[tool.peotry.dev-dependencies]  # or the poetry equivalent
dev = [
    "basedpyright", # you can pin the version here if you want, or just rely on the lockfile
]

[[tool.poetry.source]]
name = "mirrors"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.basedpyright]
typeCheckingMode = "all"
